### ISSUE TITLE
Photo process error

### ISSUE THREAD

**Issue by avi3232** [mapilio/mapilio-kit#70]
**Hi! There are some problem with Mapilio Kit v1,4.1 on Ubuntu 22,04 (VirtualBox 7 for Windows), Python version - 3,10.12, When i'm try to process timelaps photo, program failed with script errors.**

`(mapilio_venv) alex@alex-VirtualBox:~/mapilio-kit$ mapilio_kit process /media/sf_output

Processing import meta properties:   0%|                                                                  | 0/7 [00:00<?, ?files/s]

Traceback (most recent call last):

  File "/home/alex/mapilio-kit/mapilio_venv/bin/mapilio_kit", line 33, in <module>

    sys.exit(load_entry_point('mapilio-kit==1.4.1', 'console_scripts', 'mapilio_kit')())

  File "/home/alex/mapilio-kit/mapilio_venv/lib/python3.10/site-packages/mapilio_kit-1.4.1-py3.10.egg/mapilio_kit/__main__.py", line 131, in main

    args.func(vars(args))

  File "/home/alex/mapilio-kit/mapilio_venv/lib/python3.10/site-packages/mapilio_kit-1.4.1-py3.10.egg/mapilio_kit/commands/process.py", line 209, in run

    process_import_meta_properties(

  File "/home/alex/mapilio-kit/mapilio_venv/lib/python3.10/site-packages/mapilio_kit-1.4.1-py3.10.egg/mapilio_kit/process_import_meta_properties.py", line 164, in process_import_meta_properties

    import_meta_data_properties = get_import_meta_properties_exif(image)

  File "/home/alex/mapilio-kit/mapilio_venv/lib/python3.10/site-packages/mapilio_kit-1.4.1-py3.10.egg/mapilio_kit/process_import_meta_properties.py", line 116, in get_import_meta_properties_exif

    import_meta_data_properties["roll"] = ebi['roll'] if ebi['roll'] else exif.extract_roll()

TypeError: 'NoneType' object is not subscriptable

(mapilio_venv) alex@alex-VirtualBox:~/mapilio-kit$`

**Comment by bonj4** [comment]
Hi Alex, please check that your pictures are in the correct folder, if it cannot access the pictures, it will not be able to return the picture information. If you have any other questions, we will be here.

**Comment by avi3232** [comment]
> Hi Alex, please check that your pictures are in the correct folder, if it cannot access the pictures, 

Hi! Folder looks correct. EXIF v2.3.2 - correct, with date/time GPS data...

![image](https://github.com/mapilio/mapilio-kit/assets/91157543/232f0d98-c398-4a9f-9f1b-e35a2cc5e72a)

**Comment by ozcan-durak** [comment]
Hello @avi3232,

Could you kindly provide a sample folder you are attempting to upload using the kit to [support@mapilio.com](mailto:support@mapilio.com)? We would like to investigate any potential issues with our upload functionality.

**Comment by avi3232** [comment]
> We would like to investigate any potential issues with our upload functionality.

You right, other photos with native EXIF - processed & uploaded normally. There are something not compatible between Mapilio Kit and photos with EXIF, created by exiftool. I sent sample photos to support@mapilio.com.

**Comment by avi3232** [comment]
> Hello @avi3232,
> We would like to investigate any potential issues with our upload functionality.
Problem solved: In photos required EXIF tag - FocalLengthIn35mmFormat.
